### ISSUE TITLE
Rate limit exceeded when running ./download_assets_git.py

### ISSUE THREAD

**Issue by hnsl** [makehumancommunity/makehuman#104]
Error downloading object: base/skins/textures/middleage_lightskinned_male_diffuse2.png (e897c4c): Smudge error: Error downloading base/skins/textures/middleage_lightskinned_male_diffuse2.png
 (e897c4cc1b6ad5d10a7d2b2be92402feda4e772e6582dfaf0a1e8fc4621d8097): batch response: Rate limit exceeded: https://github.com/makehumancommunity/makehuman-assets.git/info/lfs/objects/batch

**Comment by hnsl** [comment]
Workaround: Manually running with authentication instead of using script:

cd ~/Documents/makehuman/v1py3
git clone git@github.com:makehumancommunity/makehuman-assets.git official_assets

**Comment by Aranuvir** [comment]
I'm not sure if this is an actual problem of the script, rather than some issues with github, some maximum download limitation or some problems with your network. Leaving the topic open for a while, to see if the problem reoccurs.

**Comment by joepal1976** [comment]
I've gotten a emailed warning that we're close to our quota on github. We're partly victims of our own success here. The github LFS  repos have quotas for both size and traffic, and you have to pay to increase them. It's possible we'll have to do that in the longer run. 

I'll assign this to myself so I remember taking a look at the quota situation and what can be done about it.

**Comment by Aranuvir** [comment]
Any updates here? Currently tried to make a setup on my Windows system. The download speed is catastrophic slow and I was reduced to about 14k. Even in the beginnings of the internet my modem was faster...

**Comment by joepal1976** [comment]
I'm already paying for double bandwidth quota since a month or two back. However, I don't see anywhere it would be possible to pay for a higher rate limit. 

Only thing I find regarding this is https://github.com/git-lfs/git-lfs/issues/3448, but there's no solution listed. 

It's possible you get placed on another rate limit if you move from using git over https to git over ssh, but I haven't tried this. It should be simple to change in the script though.

However: the general problem is the same for github LFS as it is for the asset repos. The sum total traffic generated by our users is so huge that we're on the verge of getting banned as abusive.

**Comment by Aranuvir** [comment]
Obviously we are still not banned. Therefore closing a nearly 4 years old issue.
