### ISSUE TITLE
Exporting Character with any bones

### ISSUE THREAD

**Issue by Darkolen** [makehumancommunity/makehuman#131]
Okay, I have made some cool/ decent looking people with this application, I love the output a lot, but when I want to Export them to blender Via using export in makehuman. I chose bones with toes, and some times without toes(shoes). but when I do this ( make the model into an FBX) it always comes in blender looking like a spike ball of death. the model is there, not going to lie, looking awesome, but the bones are nightmares. is there any way how to do this? or will I have to Physically rig it in blender, P.S ( if I had a job on rigging, I would have been fired on day 1) I could show pictures, and a video on how I do it, May any of you help?

**Comment by Aranuvir** [comment]
>if I had a job on rigging, I would have been fired on day 1

Wow man, that's great :grin:. I really appreciate that kind of attitude from someone who benefits from a free application, on which volunteers are working in their free time. 

That's a known bug. Current workaround: Use a different way to bring your model to blender and do a FBX export from there.
BTW if you want to fix the code on your own feel free to fix.
Since the FBX format is closed source no one really feel like diving into the code and chances are great it'll get a "won't fix".

**Comment by Darkolen** [comment]
Aranuvir I thank you, I have never known. at first, I said adobe only allows 2 free models, I need more, so this was like the first-4th thing in people's character models list, and it was free. so I downloaded it blindly, at first I loved it, and then it came to exporting I became depresses, and said This App f**kingn sucks. So I quit. and was temporarily depressed for a week, then came back to blender and said Holy sh*t I f**cking suck at blender, p.s (I'm only 14), so I went back to make human and gave it another chance, I love the results know except for this monstrosity, so I guess I will have to bring in blender, good luck to me :}
![bandicam 2020-10-24 19-45-39-016](https://user-images.githubusercontent.com/69396886/97095767-aa38f480-1631-11eb-9729-859858d1c046.jpg)
![bandicam 2020-10-24 19-45-44-161](https://user-images.githubusercontent.com/69396886/97095769-adcc7b80-1631-11eb-82c3-1d245f11e275.jpg)
