### ISSUE TITLE
Please build new ubuntu 18.04 package on PPA

### ISSUE THREAD

**Issue by manhnt9** [makehumancommunity/makehuman#15]
Regarding this issue: http://bugtracker.makehumancommunity.org/issues/1184
Please build a new ubuntu package for 18.04.
Running from source works fine but it's more difficult and time consuming for users.

**Comment by Aranuvir** [comment]
I've asked Joel to build an alpha for the ppa, now. But honestly, for Linux users  I'd recommend to run the source code in user space.
Closing this now...

**Comment by joepal1976** [comment]
Actually, I've begun preparing a PPA for 1.2.0. My plan is to have it up when we release the alpha. 

I won't build a 1.1.x PPA for 18.04 though, since it doesn't work with the numpy available in 18.04. 

(It was probably superfluous to reopen the issue here, but I'm leaving it open for now for if anyone else finds it)

**Comment by joepal1976** [comment]
There is now a functional PPA build of the 1.2.0 alpha at https://launchpad.net/~makehuman-official/+archive/ubuntu/makehuman-community
