### ISSUE TITLE
Problem of rendering Ubuntu 18.04

### ISSUE THREAD

**Issue by jlcastagner** [makehumancommunity/makehuman#151]
Hello,
In the application i see a weird effect in the rendering, the model+texture is overlayed with random shadow effects that change with the orientation of the model. This problem is not present in the mac version.
Anyone has experienced that and has solution?

thanks

**Comment by Aranuvir** [comment]
I suppose Ubuntu 18.04 is running some MH 1.1.X. The issue was more or less fixed with newer releases. I don't think we have builds for ancient Ubuntus. Best solution are either running from source or do-release-upgrade...

Rejecting this issue. Could be reopened if necessary. BTW, there's a forum for support requests.
