### ISSUE TITLE
Not starting on RTX 3070

### ISSUE THREAD

**Issue by smdanjm** [makehumancommunity/makehuman#152]
MakeHuman worked fine on my previous GPU (1060 6GB), after switching it for a 3070 it does not start at all (no splash screen). Only one error log is generated.

[python_err.txt](https://github.com/makehumancommunity/makehuman/files/5963100/python_err.txt)

**Comment by joepal1976** [comment]
For a graphics card error, this looks very strange. There is no mention of any graphics card error (the notice about opengl accelerate is normal and expected).

Are you sure that the only thing that was changed was the graphics card? Because in the log you post it looks more like a path problem.

You could try renaming or deleting the Documents\makehuman directory and see if that makes any difference.

If it does not solve the problem, can you also check if the following paths exist and can be written to without administrator privileges? 

- c:\Users\Samad
- c:\Users\Samad\Documents
- c:\Users\Samad\Documents\makehuman

**Comment by smdanjm** [comment]
Does not solve the problem, not sure what to do. The paths do exist, and if they don't then they are created by the program when I try to start it, they can be written to without admin privileges. It's just stopped working after upgrading the GPU, I used it quite a lot without problem before.

**Comment by smdanjm** [comment]
> If it does not solve the problem, can you also check if the following paths exist and can be written to without administrator privileges?

win10 controlled folder access.

Thanks for pointing me in the right direction joepal!
