### ISSUE TITLE
Community page down!

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#17]
Not very related, but the only way to get in touch. The community page seems to be down. Updated the wrong box yesterday?

**Comment by joepal1976** [comment]
No, it's unrelated, but an amusing coincidence. 

The problem is/was that my internet connection went down yesterday. After it came back up again, I hadn't noticed that I got a new IP, which made the DNS entries point in the wrong direction.

I've updated the DNS entry now, but it'll take an hour or two for it to propagate. 

I've leave this open until people seem to get access again.

**Comment by joepal1976** [comment]
As a side-note, running the MH servers in my wardrobe probably isn't an entirely optimal solution. At some point all these things should be moved to some more structured hosting.

**Comment by Aranuvir** [comment]
OK good to hear that. If we move the community to another hosting, we probably need a way to fund it.
BTW, tomorrow the DNSSEC KSK gets changed (https://www.icann.org/news/announcement-2018-08-22-en). Not sure if this applies to you.

**Comment by Aranuvir** [comment]
... it still does not work ...

**Comment by joepal1976** [comment]
Yeah, my bad. Had to update firewall rules too. Try now. 

I don't think I'm using DNSSEC.

**Comment by Aranuvir** [comment]
Reopening that issue. Cannot connect again...

**Comment by Aranuvir** [comment]
Bumping that issue again, since it still exists, though I'm not sure if you can hear me Joel!

**Comment by Aranuvir** [comment]
It is working again and therefore closing...

**Comment by joepal1976** [comment]
I was on the other side of a mountain when I started to get indications of the page being down. Should be fixed now. 

All this shows the sore need of doing something about the hosting situation...
