### ISSUE TITLE
How do you generate the mesh or can I get the mesh indices? 

### ISSUE THREAD

**Issue by poincarelee** [makehumancommunity/makehuman#170]
Hi, makehuman is really a powerful and delicate tool for human modelling. I would like to know more details by studying the source code. I saw there were about 13000 meshes for the body. Can you kindly tell me how I can get the indices of these meshes? or more precisely, which meshes are corresponding to each part of the body respectively?

**Comment by joepal1976** [comment]
You can find metadata files describing the basemesh in the MPFB2 git repo: https://github.com/makehumancommunity/mpfb2/tree/master/src/mpfb/data/mesh_metadata

Particularly this file might be of interest: https://github.com/makehumancommunity/mpfb2/blob/master/src/mpfb/data/mesh_metadata/basemesh_vertex_groups.json (the file format is group + set of [first vertex, last vertex], so that "vertgroup": { [1, 10] } means that the vertgroup group contains vertices 1 to 10. 

Closing this issue as it isn't a bug report.

**Comment by poincarelee** [comment]
Ok, thanks a lot.
