### ISSUE TITLE
Ensure symmetry in targets that are supposed to be symmetrical

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman#21]
Opening a new thread specifically for the discussion of making symmetrical targets. 

To enable plugins that might not be enabled in a release build, go to settings -> plugins.

**Comment by SerMesh** [comment]
Thanks Joel,
@Aranuvir: I enabled the "Utilities/Targets" plugin, but I fail to see how it's supposed to work. All I see is a browser panel where I can expand the "targets" tree and highlight a .target file (if any). If I click a target, the app snaps to "Modeling" and I can't see anything useful showing up. The python script doesn't suggest much either. Unless I'm doing something wrong, it looks like I'm better off analyzing symmetry issues with Modelling/Custom or an external 3D tool (or a homegrown mix of text dumps and 3D plots).

**Comment by SerMesh** [comment]
Oh, I see, those targets only become visible in Wireframe mode. It's not very helpful, though, because: 1) a color does not fully reflect the 3D displacement of a vertex (at most one can assess how smooth the  outline of a morph is, that is, the transition from blue to white, but that's a qualitative analysis at best; the other isolines are even harder to identify, especially for someone as colorblind as myself); 2) those "target influence colors" are only shown on base geometries (not on proxies), and only the main body mesh is shown in Modelling; so, if there is an issue with "tights" or other helpers, it can't be reviewed that way.

**Comment by SerMesh** [comment]
For assessing targets on helper meshes (such as tights/skirt/hair) I created some "proxies" that are actually 1:1 copies of helper meshes. Might upload them to the online repository. They are not very useful for checking symmetry issues on unmodified targets (because most often the asymmetry is quite subtle), but could help when visualizing general target smoothness as applied to "raw" helpers and not clothes.

**Comment by SerMesh** [comment]
This is probably not related to targets, but would anyone know why the joint helpers are all squishy-like in exported 3D files? All modelling sliders at their default positions, the pose is the default one too, so why would there be any deformation? The deformed boxes at spine01 and spine02 are the strangest, but all the joint helpers have some kind of deformation, except the joint-root one. (The screenshot is for Collada export, but the same oddity occurs with OBJ.)
![exportedjointhelpers](https://user-images.githubusercontent.com/40238190/50045613-340ef280-0096-11e9-916d-6c9463057403.png)

**Comment by Aranuvir** [comment]
You're not forced to use the tool. It was just a proposal. Go ahead as you like...

**Comment by SerMesh** [comment]
@Aranuvir Sorry :) and thanks a lot for enlightening me to the custom "hidden" plugins in the first place.

**Comment by SerMesh** [comment]
@joepal1976 I found the reason for the "scoliosis" observed on a supposedly symmetric random character (screenshot below). The reason is that the "Symmetry" slider in "Modelling/Random" enforces symmetry only on left-right target pairs, but still randomizes stuff like "head-trans-in|out", "neck-trans-in|out", "mouth-trans-in|out", "torso-trans-in|out"... For the Randomize feature to work as expected, the randomized value of anti-symmetric morphs should be toned down with a (1-Symmetry) factor. I will try and suggest a code fix for that, if you don't do it first (I am still focusing primarily on weight/target data).
![symmetry](https://user-images.githubusercontent.com/40238190/50052234-4bdf8880-0121-11e9-9dc5-e81651122de0.png)

**Comment by SerMesh** [comment]
P.S. I've been re-reviewing the actual symmetry issues of the targets, and it's all rather subtle as compared to the effect from anti-symmetric morphs in Randomize (above). The required fixes are really barely visible most of the time (but not always, or I wouldn't have bothered). I will commit them one folder at a time, I think, starting with the simplest ones.

**Comment by SerMesh** [comment]
@joepal1976 For the record, the six values that need to be multiplied by (1-Symmetry) upon randomization are: "head-trans-in|out", "neck-trans-in|out", "mouth-trans-in|out", "torso-trans-in|out", "hips-trans-in|out", "nose-trans-in|out". Maybe some of those are already taken care of.

**Comment by joepal1976** [comment]
I've merged the pull request now.

**Comment by joepal1976** [comment]
@black-punkduck can we close this now?

**Comment by SerMesh** [comment]
> @black-punkduck can we close this now?

Hi Joe, I wasn't aware of this having been reopened. My bad for not delivering on target symmetrization right away and turning my attention to other projects. I'll see what I can do about all this in the near future.

**Comment by joepal1976** [comment]
No worries. I just wanted to check with punkduck if his work in https://github.com/makehumancommunity/makehuman/commit/b93d7ada973e662f5741b1b05ce76819f1c572d5 hade any relation to this. 

Looking through the discussion here again, I think I might have been confusing different issues.

**Comment by SerMesh** [comment]
#21 makes sure that left and right target sliders are adjusted simultaneously where applicable. #61 seems to be about a botched "central" target that only has the one slider, but still ends up looking non-symmetric.

**Comment by black-punkduck** [comment]
All problems should be fixed now. However there are some "trans-in" and "trans-out" targets which must stay non-symmetric, they move parts horizontally. I did not touch the expressions yet and the folder asym. 

Maybe for a randomizer which works fully symmetric these trans.in and outs could be skipped (just a proposal)  :)

Here is the list, just in case:

```
# armslegs (fixed)
#
# l-foot-trans-backward.target (asymmetric skirt helper okay)
# l-foot-trans-forward.target (asymmetric skirt helper okay)
# r-foot-trans-backward.target (asymmetric skirt helper okay)
# r-foot-trans-forward.target (asymmetric skirt helper okay)
#
# asym (skipped)
#
# breast (fixed)
#
# buttocks (no problem)
#
# cheek (no problem)
#
# chin (fixed)
#
# ears (fixed)
#
# eyebrows (no problem)
#
# eyes (fixed)
#
# expression (skipped)
#
# forehead (no problem)
#
# genitals (no problem)
#
# head (no problem, only trans in/out are different)
#
# head-trans-in.target (horizontal move, no symmetry)
# head-trans-out.target (horizontal move, no symmetry)
#
#
# hip (no problem, only trans in/out are different)
#
# hip-trans-in.target (horizontal move, no symmetry)
# hip-trans-out.target (horizontal move, no symmetry)
#
# macrodetails (fixed)
#
# measure (fixed)
#
# mouth (fixed)
#
# mouth-trans-in.target (horizontal move, no symmetry)
# mouth-trans-out.target (horizontal move, no symmetry)
#
# neck (fixed)
#
# neck-trans-in.target (horizontal move, no symmetry)
# neck-trans-out.target (horizontal move, no symmetry)
#
# nose (fixed)
#
# nose-trans-in.target (horizontal move, no symmetry)
# nose-trans-out.target (horizontal move, no symmetry)
#
# pelvis (no problem)
#
# stomach (fixed)
#
# torso (fixed)
#
# torso-trans-in.target (horizontal move, no symmetry)
# torso-trans-out.target (horizontal move, no symmetry)
```

**Comment by SerMesh** [comment]
> All problems should be fixed now. However there are some "trans-in" and "trans-out" targets which must stay non-symmetric, they move parts horizontally. I did not touch the expressions yet and the folder asym.
> Maybe for a randomizer which works fully symmetric these trans.in and outs could be skipped (just a proposal)  :)

Glad to see that somebody else than me is actually going through the targets and fixing them (at least from a casual read it looks like that's what's happening). Looking forward to validating this with my own tools.

**Comment by black-punkduck** [comment]
look for the "squash merge" comments ... all other targets are untouched. New maketarget should create same syntax (number of digits etc.) now. It gives me the possibility to e.g. improve targets where skin peeks through the helper for clothes etc.

**Comment by joepal1976** [comment]
@black-punkduck : Can we close this issue?

**Comment by black-punkduck** [comment]
yes, all "trans" operations (e.g. move the head to left or right side) are used to make a body part non-symmetrical, so these should be not considered. For all others it should be okay.
