### ISSUE TITLE
Texture error when export to GLTF MPFB v2

### ISSUE THREAD

**Issue by juanmarin96** [makehumancommunity/makehuman#211]
Hi, I'm trying to export to GLTF a model generated with the plugin v2, but when I open the file, the body texture is transparent
![image](https://user-images.githubusercontent.com/19893284/188523121-dc7189e3-29fe-4fc5-8890-c2e3192b75b7.png)
Anyone cloud help me with that?

**Comment by Aranuvir** [comment]
a) Taking a look at the blender documentation, I'm not sure the exporter can handle every kind of material setup (https://docs.blender.org/manual/en/3.4/addons/import_export/scene_gltf2.html). Material setups are usually very specific to the render engine, so they probably have to be tweaked before and after export. (But tbh, I lack any experience with this exporter)

b) If you think the problem is related to MPFB, please report the bug to the specific repo. And you might want to add further error messages from the blender console.

Therefore I will reject the issue here. Maybe your question fits better in the MakeHuman forum.

**Comment by joepal1976** [comment]
I have answered this question in the MPFB tracker now: https://github.com/makehumancommunity/mpfb2/issues/54
