### ISSUE TITLE
failing to start 

### ISSUE THREAD

**Issue by joshuaruxpin** [makehumancommunity/makehuman#218]
i inspected it and it said this C:\Program Files\makehuman-community\makehuman>python makehuman.py
Traceback (most recent call last):
  File "C:\Program Files\makehuman-community\makehuman\makehuman.py", line 45, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'

**Comment by Aranuvir** [comment]
Not sure what you are doing. In case you try to run the Windows package with your own Python installation this won't work. And if you try to  run from source, please  check the README about required dependencies. 

BTW we already run a support forum.

Going to reject the issue soon, since it does not look like a bug of the application...

**Comment by Aranuvir** [comment]
No updates here. Closing for now. Can be reopened, if necessary.
