### ISSUE TITLE
Applying clothes to humans

### ISSUE THREAD

**Issue by Paar-D** [makehumancommunity/makehuman#23]
Where to find the code that applies clothes on humans and show it to us.  It is very hard to find because of the GUI on top of it. Can anyone please help me out?

**Comment by joepal1976** [comment]
Please put all support requests on the forums rather than in the bug tracker:

http://www.makehumancommunity.org/wiki/FAQ:What_is_the_prefered_method_for_contacting_the_MakeHuman_crew%3F

The code for selecting and adding a piece of clothing is here: https://github.com/makehumancommunity/makehuman/blob/master/makehuman/plugins/3_libraries_clothes_chooser.py
