### ISSUE TITLE
Windows installer: put an icon on the desktop

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman#38]
As the author of pyinstaller seems to very much dislike icons on the desktop (whereas pretty much every normal user expects them), there is no native support in pyinstaller for desktop icons.

However, as it's possible to directly change the NSIS code, it should be possible to find a workaround in order to also put an icon on the desktop. #

**Comment by joepal1976** [comment]
Well, my first swipe at this was a clear disappointment. As far as I could see, I did what was recommended in https://github.co/takluyver/pynsist/issues/95, but no desktop icon showed up. I currently don't know why.

So this will have to wait until later.

**Comment by rwbaer** [comment]
I don't know if this is helpful, but pyinstaller puts a shortcut for the start menu in C:\ProgramData\Microsoft\Windows\Start Menu\Programs when you install for all users on Windows 10.

Copying this to desktop manually is a suitable work-around.

The desktop can be represented generically as C:\Users\%USERNAME%\Desktop where %USERNAME% is replaced by windows automatically using the corresponding environmental variable.

If you install for a single user the shortcut to copy is APPDATA, but I'd need to do this install to gey the precise path.

**Comment by mdamonconnolly** [comment]
My code still has a glaring issue I'd just like to make clear. When pynsist-work/build is generated, it automatically creates the installer (before my code changes the nsis script line). While my code deletes this to create the new installer, it still adds a LOT of time to the build process just to create something that's immediately deleted right after. 
I've never used nsis before but I'm guessing there's a way to disable this, so that it will just create the build folder without actually auto-compiling the nsis script?

Thanks!

**Comment by joepal1976** [comment]
Icons are placed on desktop
