### ISSUE TITLE
Max pole issue with ponytail01 hair + catmull clark

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#48]
After running the compile tools ponytail01 hair crashes when smoothing is activated.
Here is the error message:
```
Traceback (most recent call last):
  File "./apps/catmull_clark_subdivision.py", line 230, in create
    self.vedge[ix[i],:n[i]] = ei[first[i]:][:n[i]]
ValueError: could not broadcast input array from shape (5) into shape (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/qtgui.py", line 2056, in _activate
    self.method()
  File "./core/mhmain.py", line 1481, in toggleSubdivision
    self.selectedHuman.setSubdivided(self.actions.smooth.isChecked(), True)
  File "./apps/human.py", line 467, in setSubdivided
    obj.setSubdivided(flag, *args, **kwargs)
  File "./core/guicommon.py", line 462, in setSubdivided
    self.mesh = self.getSubdivisionMesh(update)
  File "./core/guicommon.py", line 433, in getSubdivisionMesh
    self.__subdivisionMesh = cks.createSubdivisionObject(self.__seedMesh, self.staticFaceMask)
  File "./apps/catmull_clark_subdivision.py", line 521, in createSubdivisionObject
    obj.create()
  File "./apps/catmull_clark_subdivision.py", line 232, in create
    raise RuntimeError("Pole-count too low, try increasing max_pole: %s" % e)
RuntimeError: Pole-count too low, try increasing max_pole: could not broadcast input array from shape (5) into shape (4)
```

**Comment by rwbaer** [comment]
I'm guessing this is related to Punkduck's triangle-handling code?  

It makes me wonder is whether it is worth developing a utility to automatically determine max poles for asset authors if that's even possible.  I don't yet have a sense how much this number is bumped by the combination of smoothing and the new triangle code.

**Comment by Aranuvir** [comment]
At least we should check and eventually fix the whole pipeline from MakeClothes (to be ported!) down to that compile_xyz stuff...

**Comment by Aranuvir** [comment]
Any chance we get that fixed in the next time... ??

**Comment by black-punkduck** [comment]
Oops, that took some time. finally I got the same result. The compiled file is wrong:
```
Compiling binary proxy file **/v1py3/data/hair/ponytail01/ponytail01.mhpxy
Loading binary mesh **/v1py3/data/hair/ponytail01/ponytail01.npz.
NPZ-File: maxmimum number of faces for one vertex: 4
remapping weights for proxy ponytail01
```
there is no max_pole in the .mhclo ... hmm .. did I not have the same problem with some clothes a now we simply use another dictionary? I will check.

**Comment by Aranuvir** [comment]
I get the same issue after deleting the compiled file.

**Comment by black-punkduck** [comment]
yes, that is the way I test it :)

The calculated number of 4 faces neighbouring a vertex (that's the result of the algorithm) is correct for the hair, I checked the object file.  It is mainly made of 2d stripes, a skull cap and the tail starting with a cylinder and then splitted like this. 
![hair](https://user-images.githubusercontent.com/45801893/60400003-228ec300-9b6e-11e9-87dd-97276520cd92.png)

So now I ask myself, why the catmull-clark algorithm needs 5 instead of 4.

**Comment by black-punkduck** [comment]
I first thought it was this missing max_poles parameter but it is simply not needed. When I entered one I got the same problem.

The catmull-clark algorithm seems to mix some things up by the way. In the old version you could not subdivide a cube, the number of neigbouring planes of a vertex is 3. But a cube can only be subdivided with 4 new points, therefore I added this in "core/module3d.py, line 724
```
            # keep in mind that a maximum number of neighboring faces lower than 4 will crash subdiv
            if newmax < 4:
                newmax = 4

```
**when you change the values to 5 it works.**  hmmmpf ..

Because of our weird implementation of tris as ABCA quads I switched it simply of for tri-meshes. Sometimes this crashed mh completely.

The algorithm was built for closed 3d objects and not for a 2d object, also T-shaped 2d planes did have problems  ... When you look at the vertex M above it could have 4 neighbouring planes but 8 neighbouring vertices ... it is sad that this algorithm is not documented.  Should we change that to 8? Then we will use a lot of unneeded memory.

**Comment by black-punkduck** [comment]
since somewhere in MH the statement MAX_FACES = maxpoles was done (which is wrong), I now added a second algorithm to allow the calculation maxpoles in MH. Then I  use the bigger value of max_faces/max_poles for the further calculation of array size and then there should be no error. It needs a bit of testing ... when you use the ponytail in ASCII mode you can see the different values in the log. Maybe we can close the issue then ...

**Comment by rwbaer** [comment]
Maybe this is not helpful but here is what it looks like at crash when smoothing ponytail01 on Windows 10 with 1.2.0 alpha 4 build 41b65779:

![image](https://user-images.githubusercontent.com/3155051/61584796-8d9b3c00-ab13-11e9-9c3c-a54f8c268589.png)

**Comment by rwbaer** [comment]
Also, my sense (without proof) is that the smoothing algorithm has slowed considerably from before, especially before caching.

**Comment by black-punkduck** [comment]
Did you delete .npz and .mhpxy before? When you created the assets with a version in between then it will crash. In a way it is my fault or more or less that these max-poles were calculated to know the max. number of planes belonging to a vertex in the memory and the binary file. For this assets it was 4 of course. So it looks good. This number is used e.g. when you hide faces for the clothes.

But when you use catmull-clark max-poles are used in the normal sense, it happens, when the hair splits. See the small image above. So the space must be also saved in the file as well (sounds funny but the only way not to rewrite the complete code)

When you delete the files you will find the following comments in the logfile:

```

Problem loading binary mesh: ('compiled file missing: %s', '/<yourpath>/makehuman/v1py3/data/hair/ponytail01/ponytail01.npz')
Loading ASCII mesh /<yourpath>/makehuman/v1py3/data/hair/ponytail01/ponytail01.obj.
Calculated maximum number of faces for one vertex: 4
calculated maximum number of poles for one vertex: 5
remapping weights for proxy ponytail01
```
when you load a binary file with newest version you get:

```
Loading binary mesh /<yourpath>/makehuman/v1py3/data/hair/ponytail01/ponytail01.npz.
NPZ-File: maximum number of faces for one vertex: 5
```
Damned the logfile contains a typo everywhere (maxmimum) sorry ...

If your maximum number of the binary is still 4, then you used a file from a version I did inbetween - or - we have another place where assets are compiled and I did not see that until now. Any idea?

**Comment by Aranuvir** [comment]
Very strange, now things work as expected. I was sure I cleaned all npz and recompiled everything. The only explanation I can imagine, the python cache wasn't updated while running that compile stuff...

Proposing to close.
Fixed the typos with commit 2be729.

**Comment by rwbaer** [comment]
I had not deleted the binaries.  It is working under 2be72920 on windows 10.

**Comment by Aranuvir** [comment]
As it works for Rob , too, closing the topic. Could be reopened anyway, if necessary.
