### ISSUE TITLE
Makehuman working dir should be hidden

### ISSUE THREAD

**Issue by es20490446e** [makehumancommunity/makehuman#5]
In Linux the Makehuman working dir is "$HOME/makehuman". It would be nice if it was "$HOME/.config/makehuman" instead, so the user folder stays clean from config files.

**Comment by Aranuvir** [comment]
I'm not going to reject the proposal, because it merits a discussion. 

In my opinion it is not beneficial moving the makehuman folder to .config. The working directory stores more than configuration files. All custom assets, skeletons and targets as well as plugins are stored in the folder, too. There are very limited tools inside of MakeHuman to organize and remove these files. In file managers .config is usually hidden. And it is quite annoying clicking through multiple (hidden) subfolders.

As a hint for the OP: there is an undocumented command line option --home-location to change the location of the working directory on the master branch. This behaviour is altered on my branches by reading the environment variable "MH_HOME_LOCATION".

**Comment by es20490446e** [comment]
See it this way: if every application followed that design the home folder would be full of directories.

Even having the home folder full of hidden directories looks convoluted.

**Comment by Aranuvir** [comment]
As I stated above, the makehuman folder mainly does not contain configuration files, but working files. So it does not really fit in the .config folder. Is there any other folder it would fit better? Taking a look at FHS 3.0 there is no definition for any folder in /home.  We cannot even expect to find a .config folder. Technically it is trivial to check the existence of a .config folder during start up process and use it, when it exists. Though I'd recommend leaving things as they currently are. 
For those who need a different behaviour there are solutions, as I have already mentioned.

**Comment by es20490446e** [comment]
The important part in my view it's not having it visible right away in the user folder.

Preferably by making it hidden, or less conveniently by putting it into the Documents folder. Or by letting the user decide the folder.

**Comment by rwbaer** [comment]
Admittedly, I am often confused by unix-alike directory conventions, so my comments  need to be taken in that context.

Aranuvir already points out  that there are very few  configuration assets  within makehuman folder. If I had to enumerate them, I would say those ending with .ini: so settings.ini, shortcuts.ini, and maybe mouse.ini and help.ini.  These are located 1 level down in the v1 or v1py3 subdirectory.

Relative to es20490446e's last comment, I'll point out that on both Windows and Mac we do indeed put the makehuman folder in the Documents directory and not straight away in the home folder.  If it is not already there on other unix-alike OSes, this would be an internally consistent change and seems useful in many ways.

Given the normal (heavy) use of the makehuman folder by high-end MakeHuman users, it does not make much sense, and would be annoying, to hide it by default.  One could move and hide the .ini files in a configuration area, but this would not seem to address "clutter" in the home directory and they have never gotten in the way where they are.  If we move them, we have cross-platform decisions that are not clear.

**Comment by es20490446e** [comment]
That makes sense to me.

**Comment by Aranuvir** [comment]
Quote Rob:
> I'll point out that on both Windows and Mac we do indeed put the makehuman folder in the Documents directory and not straight away in the home folder. If it is not already there on other unix-alike OSes, this would be an internally consistent change and seems useful in many ways.

Best practice would be, let the user decide where to locate the makehuman folder. Unfortunately this can only be done in command line mode on first run, because the makehuman folder is created in a very early stage on start up. Assuming that most users will not start MakeHuman from a shell, this solution is obsolete.

The other solution is to move the makehuman folder to a 'Documents' folder. As I stated above, we cannot always expect to find this folder. Though normally an equivalent to a Documents folder is created by the desktop, with its name depending on the localization. This is handled by xdg-user-dirs-update and stored in .config/user-idrs.dirs. It is not to difficult to write a parser for this file and in case it returns an equivalent Documents folder, the Application will create the makehuman folder there, otherwise in $HOME.

I've created a new branch called 'xdg_folder' which introduces the new behavior. 

Fix exists, needs testing especially on platforms other than Linux, too.

**Comment by es20490446e** [comment]
Thank you. When I have a moment I will test this: added to my todo list.

**Comment by Aranuvir** [comment]
... which leads to the question if we should automatically copy data from the old location if it exists? First start could take a while then, my user data folder is round about 1GB (so a basic test was acceptable on my ssd, but not every users has a ssd in her/his system ...)

**Comment by Aranuvir** [comment]
... and of course we need to adapt the other MakeThings stuff ...

**Comment by es20490446e** [comment]
The least surprising thing would be leaving the folder were it was when created, at least if the user can choose where the folder is located.

**Comment by Aranuvir** [comment]
I don't think it is possible to move the makehuman folder at run time.

**Comment by es20490446e** [comment]
The branch works for me in Arch Linux. It creates the MakeHuman folder in ~/Documents.

**Comment by Aranuvir** [comment]
Fixed...
