### ISSUE TITLE
I get the following error before app starts

### ISSUE THREAD

**Issue by Dennis191** [makehumancommunity/makehuman#50]
roblem Event Name:	APPCRASH
  Application Name:	pythonw.exe
  Application Version:	3.6.5150.1013
  Application Timestamp:	5abbbea1
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10240.16390
  Fault Module Timestamp:	55a5bf73
  Exception Code:	40000015
  Exception Offset:	0007d85a
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1038
  Additional Information 1:	a0b8
  Additional Information 2:	a0b8c41645b11f9bcdce09b72bac04b9
  Additional Information 3:	1b72
  Additional Information 4:	1b7215fa091c93522e80c9ba42633a0d

this is on the third alpha release, downloaded onto windows7 64 bit, running on latitude e6420 laptop, integrated intel hd3000 graphics, core i5 processor.

**Comment by joepal1976** [comment]
Can you check if you got a makehuman log? 

http://www.makehumancommunity.org/wiki/FAQ:How_to_provide_a_makehuman_log_for_a_good_bug_report%3F

Also, we've introduced some fixes for intel cards lately. If you're comfortable with it, you could a) try to run the latest master code and/or b) run mh with --noshaders. Otherwise, these fixes will arrive in the next released build.

**Comment by Dennis191** [comment]
Thank you, I will try running it again 🙂

**Comment by joepal1976** [comment]
Closing this as we haven't heard anything more for a month
