### ISSUE TITLE
Eyeballs are too large

### ISSUE THREAD

**Issue by cfeck** [makehumancommunity/makehuman#59]
Steps to reproduce:
- export a default model (e.g. 100% caucasian male) using MHX2 format, "meter" unit
- import into Blender using MHX2 importer script
- compare eyeball size with spheres

Expected results:
- eyeballs have a diameter of 24 mm

Actual result:
- eyeballs have a diameter of 30 mm

Additional notes:
- Refer to attached screenshot. The smaller sphere has a diameter of 24 mm, the larger sphere of 30 mm.
- There are custom targets available to change the eyeball size, but they also change cornea size (diameter of about 11.5 mm).

**Comment by cfeck** [comment]
file:///home/pepo/MH-eyeballsize.png

**Comment by cfeck** [comment]
https://pasteboard.co/IvmmKEC.png

**Comment by Aranuvir** [comment]
Reviewing some literature, you're right, though it says "average diameter in adults", not "average diameter in male (Caucasian) adults"...
It's another questions whether those differences are visible or not. Most parts of the eyeball are hidden anyway and I doubt the increase in curvature when the eyeball gets shrunk by 20% will really be noticeable.

**Comment by cfeck** [comment]
Further investigations revealed that it is the high-poly eyes mesh which is too large. Both the placement helpers in the HM08 model, as well as the low-poly eyes object have the correct size (within 10% tolerance). Interestingly, while the low-poly eyes are smaller, they render bigger pupils with the shipped UV textures.

**Comment by Aranuvir** [comment]
Still open. @rwbaer  and @black-punkduck: Whats your opinion on this topic? I have a won't fix tendency.

**Comment by black-punkduck** [comment]
In a way yes. A won't fix, but for other reasons and it can be solved differently:
 
1) From the anatomical view the statement is correct.
2) the high-poly eyes are smaller because they are smoother. A typical catmull-clark approximation phenomenon. It is not an interpolation like e.g. Kobbelt algorithm which would re-use vertices. 
3) It is possible to create targets, for size of pupils but also for the size of eyes including sockets. Targets can also work on helpers, so that eyeballs AND sockets are changed.
4) Maybe I add this to the new still hidden version ;). Since I will not change target mechanism itself, I can upload it as a "custom" morph as well in forum.

**Comment by Aranuvir** [comment]
Ok, that's the decision.
