### ISSUE TITLE
"Calculated maximum number of faces for one vertex" multiple times on start-up

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#74]
I see this calculations are performed multiple times (>30) on start-up. There should be only two meshes (human + eyes) after starting MakeHuman and I'd consider the number of faces rather stable during a session. Could we reduce and cache that calculations?

**Comment by black-punkduck** [comment]
You get 2 information when you calculate the meshes. Typical the number of **vertex** and **poles**. It is not recalculated. So there will be always two lines per asset. Here the example (my system has an uncompiled base and eyes:

```
Problem loading binary mesh: ('compiled file missing: %s', 'data/3dobjs/base.npz')
Loading ASCII mesh data/3dobjs/base.obj.
Calculated maximum number of faces for one vertex: 5
Calculated maximum number of poles for one vertex: 5
```
is the base or body.

```
Loading ASCII mesh /data/punkduck/build/gitclones/makehuman/makehuman/data/eyes/high-poly/high-poly.obj.
Calculated maximum number of faces for one vertex: 4
Calculated maximum number of poles for one vertex: 4 

```
are the eyes.

When the system creates the background it also seems to use this routine. One face per vertex or 2 poles you will normally never get when you create a real mesh. You get it when you create a **rectangle** (or a n-gon). I dunno, could be that this is the background or the grid (or maybe a container of a background image?). Also for me it was a surprise, when I noticed it first and I had to care for it because it first crashed the program.
 
```
Imported plugin 0_modeling_background
Loading plugin 0_modeling_background
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Calculated maximum number of faces for one vertex: 1
Calculated maximum number of poles for one vertex: 2
Loaded plugin 0_modeling_background
Importing plugin 1_convert_model_tags
```
So this is definitely not a bug. Maybe I can figure out why this was done. We also can avoid the output of these lines when the number of verts is lower than two 2 not to confuse the user if you want

**Comment by Aranuvir** [comment]
Rejecting.
