### ISSUE TITLE
'Hide faces under clothes' feature not working for all Topologies

### ISSUE THREAD

**Issue by simonbroggi** [makehumancommunity/makehuman#78]
With some topologies, the Hide faces under clothes feature doesn't work properly.

![delVerts_bug_3](https://user-images.githubusercontent.com/829652/73762920-080a7100-4771-11ea-9ce2-bb14465a14e9.png)
*selected topologie: Female muscle 13442*

**Comment by Aranuvir** [comment]
The problem is that the vertex order/count in a proxy might have changed so that face indices from the body mask are not identical to the the indices of the topology.
A solution could be some sort of mask projection on the faces of the topology. But that's definitely not easy to fix...

**Comment by black-punkduck** [comment]
Just a short statetment:

well this is an old error, I know that error from my own changed meshes since years, so we did not implement a new bug in this version ;)

First I thought of a simple problem because proxy + clothes have the same z-depth. But unfortunately this was not the case

The indices were always different, that's normal for proxy meshes. I tried to understand one of the mechanisms. The one calculating the mask is in shared/proxy.py.  (transferVertexMaskToProxy)
 
proxy.ref_vIdxs is a reference, which contains 3 vertices (from mhclo file). In case of exact match it is  (vnum, 0, 0), then the vertex can also be deleted ... a bit cryptic but it is this line:

```
# a way to  figure out [ vnum, 0, 0]  :) 
#
exact_mask = ~np.any(proxy.weights[:,1:], axis=1)

```
 All other cases work for at least two hidden vertices connected to the new proxy-vertex. So another binary array for the proxy mesh is calculated which was derived from the original one. No projection used!

I am not so happy about the numpies here. I have the feeling that indexing is maybe wrong because vertsMask and proxyVertMask usually are different. But debugging a bitmask is a bit complicated  :(

I will try a non-numpy procedure to figure out the vertices to be deleted and then compare the results (simply by printing the vertex number to be deleted in both cases next). If that differs we have at least found the location. Otherwise we really have a problem somewhere, where we put all the masks together (core/guicommon.py)

**Comment by black-punkduck** [comment]
I have a solution:

in shared/proxy.py **transferVertexMaskToProxy** produces the error. Honestly I don't like that numpy functions in this case and of course I only partly understand it. I had a bad feeling and I was right (like very often when I think sth. is too weird to be correct). And yes it does not work correct, but don't ask me why. 

This code approx. inserted in line 1111 works fine. And I understand what it does  ;-)

a little bit can be optimized also in python itself, but I wanted to show how it works

```
# false = hidden face, true = unhidden
proxyVertMask = np.ones(len(proxy.ref_vIdxs), dtype=bool) # preset to unhidden

for c, elem in enumerate(proxy.weights):
     if elem[1] == 0.0 and elem[2] == 0.0:
          proxyVertMask[c] = vertsMask[proxy.ref_vIdxs[c, 0]] # will copy hidden of original mesh in case of identical value
     else:
          b1 = vertsMask[proxy.ref_vIdxs[c, 0]]  # 3 values from mhclo (references to body)
          b2 = vertsMask[proxy.ref_vIdxs[c, 1]]
          b3 = vertsMask[proxy.ref_vIdxs[c, 2]]
          l = int(b1) + int(b2) + int(b3)
          if l < 2:                   # at least two visible must be visible otherwise vertex is also hidden (false)
              proxyVertMask[c] = False

return proxyVertMask

```

**Comment by Aranuvir** [comment]
I think we fixed that, didn't we?
