### ISSUE TITLE
Windows desktop shortcut fails to launch application

### ISSUE THREAD

**Issue by lcforbes** [makehumancommunity/makehuman#90]
The Windows installer _"makehuman-community-20200517-windows.exe"_ creates a desktop shortcut. 
But this shortcut fails to launch the application because the Target's command line parameter is not surrounded by double quotes. For instance, the malformed target appears thus:

"C:\Program Files\makehuman-community\Python\pythonw.exe" C:\Program Files\makehuman-community\mhstartwrapper.py

**Comment by joepal1976** [comment]
Thank you, that's very helpful. I've been wondering why we've gotten random reports about the application not starting. 

This is obviously something which should be fixed sooner rather than later. But as a workaround, you can "install just for me" rather than "install for all users" when launching the installer.

**Comment by joepal1976** [comment]
The fix is in the latest nightly, and has been tested to work on windows 10 under "program files".
