### ISSUE TITLE
make human not opening

### ISSUE THREAD

**Issue by pirtoda** [makehumancommunity/makehuman#99]
hi 
I have windows 10 v 1909 32 bit  Blender 1.8 and 1.79
I downloaded both 1.0 and 1.1a3 
I add addon to blender and activated  

I tried to add a file openGL32 
and open v1.1a3 from start icon and and from desktop and from c://programe file

But it still does not work
Please help me

**Comment by rwbaer** [comment]
In the future this type of issue is better reported on the forum: http://www.makehumancommunity.org/forum/   will be closing this, because these are well known to work on Windows 10 given the specifics you provide.  But if this does not resolve, please DO re-post you problem on the forum. There is help there.  I

As a direct suggestion, since you are just installing now, I would suggest you go ahead and directly install the current "beta" which is way more stable than the "beta" label might suggest. In fact, the nightly build may have a few additional bug fixes that make that even better.   You can find it here: http://download.tuxfamily.org/makehuman/nightly/   Hope to see you in the forums.

**Comment by joepal1976** [comment]
The problem with MH sometimes not launching on windows when clicking the desktop icon was fixed a few days ago. Thus, you'll need the nightly build. See http://www.makehumancommunity.org/wiki/FAQ:Which_version_of_MakeHuman_should_I_download%3F

**Comment by pirtoda** [comment]
hi thank you for response
1.1.1 v give me fatal Error 
![image](https://user-images.githubusercontent.com/66679634/84398979-816f1000-abf8-11ea-8138-1e5843e5e651.png)

1.2.0a4 
not running ( I use start menu)
no erreur message

nightly 
after instalation  told me this app can run 
![image](https://user-images.githubusercontent.com/66679634/84399716-15d97280-abf9-11ea-81d9-eecc62b0296e.png)

The problems are different, so I think at least one of them can be solved. I really need this program

I am sorry, but I do not have an account in  forum and I don’t know how to use it

**Comment by rwbaer** [comment]
To add to what Joel says, you should still be able to start the 1.2.0 alpha 4 from the start menu.  it is just the desktop icon that is broken.

**Comment by joepal1976** [comment]
Yes, it's currently a limitation that you need to have a 64-bit windows to run the builds.
